/**
 * Setup recipe for a headless Linux box. On a machine with no desktop session there is usually no
 * D-Bus session bus and no running gnome-keyring, so every keystore call fails — or worse,
 * succeeds into the memory-backed session collection and is lost at the next reboot.
 */
export function linuxKeyringGuide(): string {
  return [
    'HEADLESS LINUX (SSH, no desktop session)',
    '',
    '  Secrets live in the Secret Service. Without a D-Bus session bus and a running',
    '  gnome-keyring, there is nothing to store them in — and with no keyring file on disk,',
    '  libsecret falls back to a memory-only collection that is lost at the next reboot.',
    '',
    '  Check what exists:',
    '    ls -la ~/.local/share/keyrings/     # a *.keyring file means storage survives a reboot',
    '',
    '  Install it:',
    '    sudo apt-get install -y gnome-keyring dbus-x11',
    '',
    '  Then add this to your shell startup file, ABOVE the claudefob block:',
    '',
    '    # D-Bus session bus: prefer the systemd user bus, fall back to launching one.',
    '    if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then',
    '      if [ -S "/run/user/$(id -u)/bus" ]; then',
    '        export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"',
    '      else',
    '        export $(dbus-launch)',
    '      fi',
    '    fi',
    '',
    '    # gnome-keyring secrets component, unlocked with an empty passphrase.',
    '    if [ -z "${GNOME_KEYRING_CONTROL:-}" ]; then',
    '      eval "$(printf \'\\n\' | gnome-keyring-daemon --unlock --components=secrets 2>/dev/null)"',
    '    fi',
    '',
    '  Both guards matter: without them every new session spawns another bus and another daemon.',
    '',
    '  Optional, and recommended if you log in often:',
    '    sudo loginctl enable-linger $USER',
    '  This keeps your user session and its bus alive between logins, so sessions reuse one bus',
    '  instead of launching a pair each time. It is not required — the fallback above covers it.',
    '',
    '  Verify it really persists:',
    '    claudefob add test        # any value',
    '    sudo reboot',
    '    claudefob use test        # still works? storage is real',
    '',
    '  Note: an empty passphrase is what lets the keyring unlock unattended, and it also means the',
    '  encryption protects nothing — the file is readable by anyone who can read it. What actually',
    '  guards it is the 0700 on ~/.local/share/keyrings/. Use a real passphrase (and unlock it per',
    '  session) if that box holds anything you would not put in a chmod 600 file.',
    '',
    '  Revealing a token (`claudefob show`) needs sudo here: pkexec has no polkit agent to ask on',
    '  a headless box, so claudefob prompts with sudo instead.',
  ].join('\n')
}
